In [2]:
import numpy as np
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
a = np.array([[1,2],[3,4]]) # 定义二维数组
a_m = np.matrix(a) # 矩阵
print(a)
print(a_m)
print(type(a))
print(type(a_m))
print(a*a) # 数组乘法
print(a_m*a_m) # 矩阵乘法


print(a+a) # array数组位置加法
c = [1,2]
print(c+c) # python数组数组拼接

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
<class 'numpy.matrix'>
[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]
[[2 4]
 [6 8]]
[1, 2, 1, 2]


In [13]:
# python数组加法必须手动实现，否则会变成拼接
d = [x+1 for x in range(5)]
for i in range(5):
    d[i] = d[i]+d[i]

print(d)


[2, 4, 6, 8, 10]


In [14]:
print(type(a))
print(a.ndim)

<class 'numpy.ndarray'>
2


In [ ]:
a = np.array((1,2,3))
b = np.array(a, copy=True) # 复制一份
c = np.array(a, copy=False) # 复用
e = np.array(a) # 默认copy=True
print(id(a))
print(id(b))
print(id(c))
print(id(e))

2063635893680
2063636236976
2063635893680
2063635904624


In [19]:
a = np.linspace(1,10,10,endpoint=True, dtype=float)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [20]:
a.shape

(10,)

In [23]:
b = a.reshape(2,5) #更改形状
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [25]:
b.itemsize # 元素字节数

8

In [44]:
print(b[...,2:]) # 全部行
print(a[1::2])
print(a[::-1]) # 倒序

print(b[...][0], b[0])

[[ 3.  4.  5.]
 [ 8.  9. 10.]]
[ 2.  4.  6.  8. 10.]
[10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]
[1. 2. 3. 4. 5.] [1. 2. 3. 4. 5.]


In [55]:

print(b)
print(b[[0,1],[0,1]]) # 二维数组选取(0,0),(1,1)
print(b[0:1][0,1])

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
[1. 7.]
2.0


In [104]:
# 广播：从最后维度向前比较，都满足则可以广播

In [ ]:
# array:mean,max
# numpy.random:rand,randn,seed
# numpy:append,insert,delete,unique

In [ ]:
a = np.arange(12).reshape(3,4)
print(a)
a.mean(axis = 0) # 跨行平均

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([4., 5., 6., 7.])

In [58]:
a = np.arange(12).reshape(3,4)
print(a)
a.max(axis = 0) # 跨行最大

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 8,  9, 10, 11])

In [85]:
print(np.random.randn(4,2)) # 标准正态分布，均值0，标准差1

[[ 0.42105072 -1.06560298]
 [-0.88623967 -0.47573349]
 [ 0.68968231  0.56119218]
 [-1.30554851 -1.11947526]]


In [90]:
np.random.seed(11) # 影响下一行
print(np.random.rand(4,2)) # 均匀分布

np.random.seed(11)
print(np.random.rand(4,2)) # 均匀分布

[[0.18026969 0.01947524]
 [0.46321853 0.72493393]
 [0.4202036  0.4854271 ]
 [0.01278081 0.48737161]]
[[0.18026969 0.01947524]
 [0.46321853 0.72493393]
 [0.4202036  0.4854271 ]
 [0.01278081 0.48737161]]


In [99]:
a = np.array([[1,2,3],[4,5,6]])
print(np.append(a, [[1,1,1]], axis=0)) # 必须维度级别和最后一维相同,0表示跨行append
print(np.append(a, [[1,2],[1,2]], axis=1))

[[1 2 3]
 [4 5 6]
 [1 1 1]]
[[1 2 3 1 2]
 [4 5 6 1 2]]


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(np.insert(a, 1, [0,0,0], axis=0))
print(np.delete(a, 1, axis=0)) # 跨行删除

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [0 0 0]
 [4 5 6]]
[[1 2 3]]


In [ ]:
a = np.array([1,2,2,3,4,5])
b = np.unique(a) #去重
print(a, b)

[1 2 2 3 4 5] [1 2 3 4 5]
