In [2]:
import torch
torch.cuda.is_available()

True

In [ ]:
# Tensor，eye，zeros，ones，arange，linspace，logspace
# rand，randn，randint

In [ ]:
a = torch.Tensor([[1,2],[3,4]]) # 浮点张量
a

tensor([[1., 2.],
        [3., 4.]])

In [9]:
a = torch.eye(2,2)
print(a)
print(torch.zeros(2,2))
print(torch.ones(2,2))

tensor([[1., 0.],
        [0., 1.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [ ]:
print(torch.arange(1,11,2))
print(torch.linspace(1,10,5)) # steps:等差数列数量
print(torch.logspace(1,9,5)) # number:次方数，等比数列

tensor([1, 3, 5, 7, 9])
tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])
tensor([1.0000e+01, 1.0000e+03, 1.0000e+05, 1.0000e+07, 1.0000e+09])


In [ ]:
print(torch.rand(3,3)) # 随机

tensor([[0.9481, 0.9904, 0.7958],
        [0.6693, 0.6440, 0.6472],
        [0.7357, 0.4237, 0.4825]])


In [ ]:
print(torch.randn(3,3)) # 正态分布

tensor([[-0.9666, -1.2728, -1.0110],
        [ 1.5587,  0.1686,  0.7138],
        [-0.7427, -1.4066, -1.3344]])


In [ ]:
print(torch.randint(1,3,(2,2)))

tensor([[2, 1],
        [2, 2]])


In [ ]:
# torch:from_numpy(torch.Tensor & numpy.ndarray转换)
# torch.Tensor:shape

In [45]:
# ndarray 和 tensor转换
import numpy as np
a = np.array([3,2,4])
t = torch.from_numpy(a)
a,type(a), t, type(t)

(array([3, 2, 4]), numpy.ndarray, tensor([3, 2, 4]), torch.Tensor)

In [30]:
a = torch.Tensor(2,3,128,128)
print(a.shape) # 2张图
print(a[0].shape) # 一张图
print(a[0][0].shape) # 宽高
print(a[0][0][0].shape) # 行

torch.Size([2, 3, 128, 128])
torch.Size([3, 128, 128])
torch.Size([128, 128])
torch.Size([128])


In [ ]:
# 一部分切片 a[start:end:step]
a = torch.Tensor(2,3,128,128)
# a[0] = -1
# a[1] = 1
print(a[:1,:,:].shape) # 第一张图
print(a[:1,:1,:].shape) # 第一个通道R
print(a[:1,:1,:64,:64].shape) # 面积1/4
print(a[:1,:1,:128:2,:128:2].shape) # step=2


torch.Size([1, 3, 128, 128])
torch.Size([1, 1, 128, 128])
torch.Size([1, 1, 64, 64])
torch.Size([1, 1, 64, 64])


In [ ]:
# Tensor：reshape,unsqueeze，squeeze，transpose，permute，expand

In [47]:
# 维度变换reshape！！！重要。
a = torch.Tensor(2,3,64,64)
print(a.reshape(2,3,-1).shape)
print(a.reshape(4,-1).shape)

torch.Size([2, 3, 4096])
torch.Size([4, 6144])


In [ ]:
a = torch.Tensor(2,1,64,64) # 2张灰度图
print(a.unsqueeze(0).shape) # 增加维度
print(a.squeeze(1).shape) # 降低维度（必须为1，否则不生效）

torch.Size([1, 2, 1, 64, 64])
torch.Size([2, 64, 64])


In [ ]:
a = torch.Tensor(2,1,64,64)
print(a.transpose(0,1).shape) # 维度交换
print(a.permute(1,0,3,2).shape) # 必须是全部维度

torch.Size([1, 2, 64, 64])
torch.Size([1, 2, 64, 64])


In [60]:
a = torch.Tensor(2,1,64,64)
print(a.expand(2,3,64,64).shape) # 扩展维度，要求初始为1

torch.Size([2, 3, 64, 64])
